[project]
name = "simplearmory"
version = "2.0.0"
description = "Refactor of Simple Armory"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "tqdm>=4.67.1",
]
